IoC.Web/Controllers/BaseController.cs
using System.Web.Mvc;

namespace IoC.Web.Controllers
{
    public class BaseController : Controller
    {
        // GET: Base
        public virtual ActionResult Index()
        {
            return View();
        }
    }
}

IoC.Web/Controllers/TestController.cs
using Castle.Core.Logging;
using IoC.Business.Services.Contracts;
using IoC.ViewModels.Models;
using System;
using System.Web.Mvc;

namespace IoC.Web.Controllers
{
    public class TestController : BaseController
    {
        private readonly ITestService _testService;
        public ILogger Logger { get; set; } = NullLogger.Instance;

        public TestController(ITestService testService)
        {
            _testService = testService;
        }

        public override ActionResult Index()
        {
            return View(_testService.GetAllUsers());
        }

        public ActionResult Create()
        {
            UserViewModel userViewModel = new UserViewModel
            {
                Companies = _testService.GetAllCompanies()
            };
            return View(userViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserViewModel user)
        {
            if (ModelState.ContainsKey("ChosedCompany.Id"))
            {
                var existCompany = _testService.GetCompanyById(user.ChosedCompany.Id);
                if (existCompany != null)
                {
                    user.ChosedCompany = existCompany;
                    _testService.AddUser(user);
                    Logger.Info("User added to database");
                }
                else
                {
                    Logger.Error("Add user failed");
                }
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid id)
        {
            UserViewModel userViewModel = _testService.GetUserById(id);
            userViewModel.Companies = _testService.GetAllCompanies();
            return View(userViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserViewModel user)
        {
            _testService.UpdateUser(user);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(Guid id)
        {
            return View(_testService.GetUserById(id));
        }

        [HttpDelete]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(UserViewModel user)
        { 
            _testService.DeleteUser(user);
            return RedirectToAction("Index");
        }
    }
}

IoC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("OxagileTask", "Index", "Test", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

IoC.Web/Views/Test/Create.cshtml
@using IoC.Business.Services.Contracts
@model IoC.ViewModels.Models.UserViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>UserViewModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-12">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="row">
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            @Html.LabelFor(model => model.ChosedCompany.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="row">
                <div class="col-md-6">
                    @Html.DropDownList("ChosedCompany.Id", new SelectList(Model.Companies, "Id", "Name"), new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-secondary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IoC.Web/Views/Test/Delete.cshtml
@model IoC.ViewModels.Models.UserViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ChosedCompany.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ChosedCompany.Name)
        </dd>
    </dl>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HttpMethodOverride(HttpVerbs.Delete)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-secondary" /> |
            @Html.ActionLink("Back to List", "Index");
        </div>
    }
</div>

IoC.Web/Views/Test/Edit.cshtml
@model IoC.ViewModels.Models.UserViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="row">
                    <div class="col-md-6">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.LabelFor(model => model.ChosedCompany.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="row">
                    <div class="col-md-6">
                        @Html.DropDownList("ChosedCompany.Id", new SelectList(Model.Companies, "Id", "Name"), new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-secondary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IoC.Web/Views/Test/Index.cshtml
@model IEnumerable<IoC.ViewModels.Models.UserViewModel>

@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <thead class="thead-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChosedCompany.Name)
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChosedCompany.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>